#include <stdio.h>
#include <ctype.h>
#include <stdlib.h>

void writeheader(char *l, FILE *f)
{
    fprintf(f,";; Swappable Library [%s] ;;\n"
              ";; This file generated by genpre ;;\n"
              ";; This is a pre-stub ;;\n"
              "psect lowpage\n"
              "top:\n",l);

}

void writetrailer(char *l, FILE *f)
{
    fprintf(f,"defb 0\n"
              "bot:\n"
              "defs top+2000h-bot\n"
              "psect text\n"
              "psect data\n"
              "psect bss\n");
}

void process_symbol(char *s, FILE *f)
{
    if(s[0]!='_' || s[1]!='_' || s[2]!='S') return; /* Stub-Prefix __S */
    fprintf(f,"defm '%s'\n"
              "defb 0\n"
              "defw %s\n"
              "global %s\n",s,s,s);
}

main(int argc, char **argv)
{
    FILE *in;
    FILE *out;
    char runstring[256];
    char buffer[1024];

    if(argc!=2)
    {
        fprintf(stderr,"genpre libname\n  Libname should omit the"
        " extension.\n");
        return 2;
    }
    strcpy(runstring,argv[1]);
    strcat(runstring,".lib");
    if(NULL==(in=fopen(runstring,"r")))
    {
        fprintf(stderr,"Cannot open %s.\n",runstring);
        return 3;
    }
    fclose(in);
    sprintf(runstring,"zxlibr s %s.lib > %s.sym",argv[1],argv[1]);
    fprintf(stderr,"Executing: %s\n",runstring);
    if(system(runstring)) return 1;
    strcpy(runstring,argv[1]);
    strcat(runstring,".sym");
    in=fopen(runstring,"r");
    if(NULL==in)
    {
        fprintf(stderr,"Cannot open %s.\n",runstring);
        return 7;
    }
    strcpy(runstring,argv[1]);
    strcat(runstring,".pre");
    out=fopen(runstring,"w");
    if(NULL==out)
    {
        fprintf(stderr,"Cannot open %s.\n",runstring);
        return 7;
    }
    fprintf(stderr,"Writing %s.\n",runstring);
    writeheader(argv[1],out);
    while(NULL!=fgets(buffer,1024,in))
    {
        char *s;
        char *s1;
        int done;
        done=0;
        s=buffer;
        while(!isspace(*s)) s++;  /* skip any module name */
        while(*s)
        {
           while(*s && isspace(*s)) s++;   /* skip spaces before ID */
           if(!*s) break;
           switch(*s)
           {
              case 'U': s++;
                        while(*s && isspace(*s)) s++;
                        while(*s && !isspace(*s)) s++;
			if(!*s) goto ENDOFSTRING;
			break;
	      case 'D': s++;
			while(*s && isspace(*s)) s++;
			s1=s;
			while(*s && !isspace(*s)) s++;
			if(!*s) done=1;
			*s=0;
			s++;
			process_symbol(s1,out);
			if(done) goto ENDOFSTRING;
			break;
	    default: fprintf(stderr,"Unknown identifier `%c'\n",*s);
	      return 5;
	  }
        }
        ENDOFSTRING:;
    }
    fclose(in);
    writetrailer(argv[1],out);
    fclose(out);
    return 0;
}

