#include <stdio.h>
#include <string.h>

void make_stub(char *n,unsigned address,FILE *f)
{
    char stubname[256];
    stubname[0]='_';
    strcpy(stubname+1,n+3);
    fprintf(f,
      "global %s,%s\n"
      "%s:\n"
      "ld hl, 0%xh\n"
      "jp DoRoutine\n\n",n,stubname,stubname,address);
}

void make_trailer(char *n, FILE *f)
{
    fprintf(f,
      ";; end of stubs ;;\n");
}

void make_header(char *n, unsigned int libpagenumber, FILE *f)
{
    fprintf(f,
      ";; stubs generated by genstub.c for %s\n"
      "psect lowpage\n\n"
      "LibPageLow equ 0%xh\n"
      "LibPageHigh equ 0%xh\n"
      "ProgPageLow equ 07\n"
      "ProgPageHigh equ 4\n\n"
      "DoRoutine:\n"
      "ld a,LibPageLow\n"
      "out (3),a\n"
      "ld a,LibPageHigh\n"
      "out (4),a\n"
      "pop bc\n"
      "ld a,c\n"
      "ld (Return+1),a\n"
      "ld a,b\n"
      "ld (Return+2),a\n"
      "ld de,CleanUp\n"
      "push de\n"
      "jp (hl)\n"
      "CleanUp:\n"
      "ld a,ProgPageLow\n"
      "out (3),a\n"
      "ld a,ProgPageHigh\n"
      "out (4),a\n"
      "Return:\n"
      "jp 0000\n\n\n",n,libpagenumber&0xff,libpagenumber>>8);
}

main(int argc, char **argv)
{
    char name[256];
    unsigned short address;
    unsigned libpagenumber=0x408;
    FILE *in,*out;
    int c;
    if(argc!=2 && argc!=3)
    {
        fprintf(stderr,"genstub name [libpagenumber]\n");
        return 3;
    }
    strcpy(name,argv[1]);
    strcat(name,".bin");
    in=fopen(name,"rb");
    if(in==NULL)
    {
        fprintf(stderr,"Cannot open %s.\n",name);
        return 4;
    }
    strcpy(name,argv[1]);
    strcat(name,".as");
    out=fopen(name,"w");
    if(out==NULL)
    {
        fprintf(stderr,"Cannot open %s.\n",name);
	return 5;
    }
    if(argc==3) sscanf(argv[2],"%x",&libpagenumber);
    make_header(argv[1],(unsigned short)libpagenumber,out);
    while(!feof(in))
    {
        char *s;
        s=name;
        while(*s=fgetc(in)) s++;
        if(s==name) break;
        *(char*)&address = fgetc(in);
	((char*)&address)[1]=fgetc(in);
	make_stub(name,address,out);
    }
    make_trailer(argv[1],out);
    strcpy(name,argv[1]);
    strcat(name,".slb");
    out=fopen(name,"wb");
    if(out==NULL)
    {
	fprintf(stderr,"Cannot open %s.\n",name);
	return 6;
    }
    fseek(in,8192,SEEK_SET);
    while(-1!=(c=fgetc(in))) fputc(c,out);
    fclose(in);
    fclose(out);
    return 0;
}
