;; stubs generated by genstub.c for Test
psect lowpage
LibPageHigh equ 4
ProgPageLow equ 07
ProgPageHigh equ 4
global _ozbox,__Sozbox
_ozbox:
ld a,LibPageLow
out (3),a
ld a,LibPageHigh
out (4),a
pop hl
ld a,l
ld (3f+1),a
ld a,h
ld (3f+2),a
call __Sozbox
1:
ld a,ProgPageLow
out (3),a
ld a,ProgPageHigh
out (4),a
3:
jp 0000
psect data
psect bss
