;; stubs generated by genstub.c for ozbox
psect lowpage

LibPageLow equ 08h
LibPageHigh equ 04h
ProgPageLow equ 07
ProgPageHigh equ 4

DoRoutine:
ld a,LibPageLow
out (3),a
ld a,LibPageHigh
out (4),a
pop bc
ld a,c
ld (Return+1),a
ld a,b
ld (Return+2),a
ld de,CleanUp
push de
jp (hl)
CleanUp:
ld a,ProgPageLow
out (3),a
ld a,ProgPageHigh
out (4),a
Return:
jp 0000


global __Sozbox,_ozbox
_ozbox:
ld hl, 0a000h
jp DoRoutine

;; end of stubs ;;
