@echo off
echo This does some pre-distribution stuff.
echo If you're not Alexander Pruss, you should press CTRL-BREAK now.
pause
call uninstp
cd edit
call distr.bat
cd ..
call uninstp
del wizterm\*.map
del wizterm\*.bak
del wizterm\*.aso
del wizterm\*.bin
del wizterm\*.lib
del wizterm\*.obj
del fonts\*.map
del fonts\*.bak
del fonts\*.aso
del fonts\*.bin
del fonts\*.lib
del fonts\*.obj
del fonts\*.tds
del misc\*.map
del misc\*.bak
del misc\*.aso
del misc\*.bin
del misc\*.lib
del misc\*.obj
del othello\*.map
del othello\*.bak
del othello\*.aso
del othello\*.bin
del othello\*.lib
del othello\*.obj
del gfx\*.map
del gfx\*.bak
del gfx\*.aso
del gfx\*.bin
del gfx\*.lib
del gfx\*.obj
del week\*.map
del week\*.bak
del week\*.aso
del week\*.bin
del week\*.lib
del week\*.obj
del exp\*.map
del exp\*.bak
del exp\*.aso
del exp\*.bin
del exp\*.lib
del exp\*.obj
del file\*.map
del file\*.bak
del file\*.aso
del file\*.bin
del file\*.lib
del file\*.obj
del file\*.tds
del wiztris\*.map
del wiztris\*.bak
del wiztris\*.aso
del wiztris\*.bin
del wiztris\*.lib
del wiztris\*.obj
del pix\*.map
del pix\*.bak
del pix\*.aso
del pix\*.bin
del pix\*.lib
del pix\*.obj
del indexby\*.map
del indexby\*.bak
del indexby\*.aso
del indexby\*.bin
del indexby\*.lib
del indexby\*.obj
del deleter\*.map
del deleter\*.bak
del deleter\*.aso
del deleter\*.bin
del deleter\*.lib
del deleter\*.obj
del menu\*.map
del menu\*.bak
del menu\*.aso
del menu\*.bin
del menu\*.lib
del menu\*.obj
del clock\*.map
del clock\*.bak
del clock\*.aso
del clock\*.bin
del clock\*.lib
del clock\*.obj
del edit\*.map
del edit\*.bak
del edit\*.aso
del edit\*.bin
del edit\*.lib
del edit\*.obj
del key\*.map
del key\*.bak
del key\*.aso
del key\*.bin
del key\*.lib
del key\*.obj
del same\*.map
del same\*.bak
del same\*.aso
del same\*.bin
del same\*.lib
del same\*.obj
del chess\*.map
del chess\*.bak
del chess\*.aso
del chess\*.bin
del chess\*.lib
del chess\*.obj
del 3d\*.map
del 3d\*.bak
del 3d\*.aso
del 3d\*.bin
del 3d\*.obj
del liboz\*.bak
del liboz\*.aso
del liboz\*.map
