all: archess.wzd

OBJS2 = ARMOV.obj AREVAL.obj ARGEN.obj ARLIB.obj ARVAR.obj IO.obj IOLIB.obj \
IOSCREEN.obj IOSETHLP.obj SEARCH.obj SLIB.obj tc_port.obj scr8x8.obj putch.obj \
smallstr.obj misc.obj

archess.lib: $(OBJS2)
        zxecho lib.arg r archess.lib $(OBJS2)
        xlibr lib.arg

.c.obj:
        zcc -ox -c -DOZ7XX $*.c

.as.obj:
        zxas $*.as

archess.wzd: archess.obj archess.lib
        zcc -z archess.obj archess.lib
