There are instructions below, under the license.  Please read everything, including license and instructions, before downloading.
BY DOWNLOADING YOU SIGNIFY YOU HAVE READ AND AGREED TO ALL OF THE CONDITIONS LISTED HERE.  This is a C/assembly program.  It is possible for a C/assembly program to damage data and even to make your organizer inoperable.  USE AT YOUR OWN RISK.  NO GUARANTEES ARE MADE. By downloading this program to your organizer you agree not to hold the author(s) responsible for any damage to data, hardware or anything else. IF ANY OF THESE CONDITIONS ARE NOT PERMITTED BY APPLICABLE LAW, YOU ARE NOT LEGALLY PERMITTED TO DOWNLOAD OR USE THE PROGRAM. This program may be freely distributed but only provided that this description is included in unmodified format.  This program is copyright (c) 2000-2001 Alexander R Pruss.
It is VERY strongly recommended you back up your Wizard before running C/assembler programs, especially ones like Loader that create files.
NOTE: If a C/assembly program hangs due to a bug, you may need to flip the battery switch on the bottom of the Wizard back and forth.  If the Wizard does not respond to this, taking the batteries out for half a minute should help.  If this doesn't help, you've read the WARNING above.  None of this should be necessary, but no guarantees are made.
BASIC INSTRUCTIONS: Frommemo converts specially formatted memos put out by utilities such as Benjamin Green's ProgToMemo, Alexander Pruss's ToMemo, or Chris Lyons' OzGut Converter into files in the C-based file system on the Wizard.  These files are stored in schedule entries for January 1, 1901.  Because each schedule entry has to be under around 2000 bytes, any one file spans several schedule entries.  Do not modify these schedule entries manually, but feel free to delete the entries with the filename in the description.
You may occasionally experience problems synchronizing these schedule entries with DayTimer.  The program data inside these entries is NOT synchronized with DayTimer;  only the labels are.
This program is useless without a program like OzGut, SecureEdit, Loader 2.x, or ZMachine which can make use of the files created.

TECHNICAL INFORMATION: This program is written in Hi-Tech C and Z80 assembly language.  For the Hi-Tech C SDK, see www.ozdev.com under "win32 software".
