md ..\..\edit
copy misc-s.as ..\..\edit
del misc-s.as
copy smain.* ..\..\edit
del smain.*
copy ..\..\edit\smain.xbm
copy secure.* ..\..\edit
del secure.*
copy menu.* ..\..\edit
del menu.*
copy makesec ..\..\edit
del makesec
copy 32ksec.* ..\..\edit
del 32ksec.*
copy randhbit.* ..\..\edit
del randhbit.*
copy secvars.* ..\..\edit
del secvars.*
del edit-s.*
del show-s.*
del clip-s.*
del *.aso
del *.bak
del *.bin
del *.lib
del *.obj
del *.arg

